OptimizationChain
TiendaNube/image-compression-lib pull request #7
Opened 2021-05-06 02:20 UTC by jonybecker

Add custom optimizer configurations and build a new default chain

2021-05-12 14:16 UTC, ecastro98 commented on docker-compose.cli.yml
> +    image: cytopia/php-cs-fixer:latest-php7.2
Nos conviene actualizar esto cuando la versión mínima de la librería es 7.0?

2021-05-12 14:16 UTC, ecastro98 commented on src/DefaultImageOptimizer.php
> +
```suggestion
```

2021-05-12 14:16 UTC, ecastro98 commented on src/DefaultImageOptimizer.php
> +use Spatie\ImageOptimizer\OptimizerChain;
Se usa este import?

2021-05-12 14:16 UTC, ecastro98 commented on src/Optimizers/Factories/Jpegoptim.php
> +use Spatie\ImageOptimizer\Optimizers\Jpegoptim as SpazieJpegoptim;
Puede ser que hayas querido escribir `Spatie` en vez de `Spazie`?

2021-05-12 14:16 UTC, ecastro98 commented on src/Optimizers/OptimizerListService.php
> +
```suggestion
    public static function getOptimizerChain()
    {
```

2021-05-12 14:16 UTC, ecastro98 commented on tests/Optimizers/OptimizerListServiceTest.php
> +    use PHPMock;
Qué hace PHPMock?

2021-05-12 18:00 UTC, juanmanuel-perez commented on src/Optimizers/OptimizerListService.php
> +    public static function getOptimizerChain(){
Esta funcion seria el punto de entrada por lo cual, al no tener inyeccion de dependencias, la vamos a tener que dejar statica. Pero luego, internamente se podria evitar utilizar static para evitar usar alias en los test?

2021-05-14 21:22 UTC, jonybecker commented on src/Optimizers/OptimizerListService.php
> +    public static function getOptimizerChain(){
ahi lo cambie al constructor, no tenia sentido armar la cadena en cada imagen.
Si mantuve los statics para los metodos que crean y agregan los optimizadores porque no veo sentido de crear un objeto, que opinas?

2021-05-14 21:34 UTC, jonybecker commented on src/DefaultImageOptimizer.php
> +use Spatie\ImageOptimizer\OptimizerChain;
ahora si :P

2021-05-14 21:34 UTC, jonybecker commented on src/Optimizers/Factories/Jpegoptim.php
> +use Spatie\ImageOptimizer\Optimizers\Jpegoptim as SpazieJpegoptim;
Dedazo!, ahi lo cambie

2021-05-14 22:17 UTC, jonybecker commented on tests/Optimizers/OptimizerListServiceTest.php
> +    use PHPMock;
mockea functions, pero me lo lleve mal a todos los tests, ahi lo saque. solo tiene que quedar en el DefaultImageOptimizer por el `exec`

2021-05-17 18:05 UTC, ecastro98 submitted a review, later dismissed

2021-05-17 18:05 UTC, ecastro98 commented on src/DefaultImageOptimizer.php
> +    public function __construct(OptimizerChain $optimizerChain = null)
Esto se va a llamar desde afuera de la libreria no? Conviene tener nuestro propia inferface de `OptimizerChain`? Creo que de esta forma estariamos obligando al cliente a utilizar el `OptimizerChain` de Spatie y no algún componente de nuestra librería. No se si me hago entender.

2021-05-17 18:05 UTC, ecastro98 commented on src/Optimizers/OptimizerListService.php
> +            $optimizer::addOptimizerTo($optimizerChain);
Tiene sentido cambiar el método estatico al normal y en la propiedad poner instancias?
```php
private $optimizers = [        
    new JpgOptimizer(),        
    new PngOptimizer(),    
];

$optimizer->addOptimizerTo($optimizerChain);
```

2021-05-26 18:36 UTC, jonybecker commented on src/Optimizers/OptimizerListService.php
> +            $optimizer::addOptimizerTo($optimizerChain);
Tiene sentido pero al no poder instanciar dentro del atributo, estoy obligado a hacerlo por fuera. ahi creo que terminamos ensuciando(o dejando menos claro) el codigo. Que opinas?

2021-05-26 18:39 UTC, jonybecker commented on src/DefaultImageOptimizer.php
> +    public function __construct(OptimizerChain $optimizerChain = null)
Te entendi perfecto, gracias. Por el momento lo dejaría asi hasta que llegue el momento en donde necesitemos usar otro optimizador que no esté dentro de Spatie, te parece?

2021-05-26 19:09 UTC, juanmanuel-perez commented on src/DefaultImageOptimizer.php
> +    public function __construct(OptimizerChain $optimizerChain = null)
Igualmente, en el caso de querer hacerlo ahora lo dejaria para otro PR por cuestiones de legibilidad.

2021-05-30 00:19 UTC, martin-sanjuan requested changes

2021-05-30 00:19 UTC, martin-sanjuan commented on tests/Optimizers/JpgOptimizerTest.php
> +            ->once();
Estas testeando todo el proceso interno, lo que hace tu test muy sensible a cambios que no deberían afectarte. 

Supongamos que `Jpegoptim` ya no usa mas `create`, y ahora usa `get`, el refactor en `JpgOptimizer` no debería  cambiar el test, por que la función sigue siendo exactamente la misma, pero con una implementación diferente. En lugar del test, darte la seguridad de que mantuviste el BAU podría romperse porque `create` dejo de existir por ejemplo. 

Pensando en lo que queres testear, podrias hacer simplemente 

```php 
$chain = new OptimizerChain();
JpgOptimizer::addOptimizerTo($chain);

$addedOptimizer = $chain->getOptimizers()[0] ?? null;
$this->assertInstanceOf(SpatieJpg::class, $addedOptimizer); 
```

2021-05-30 00:19 UTC, martin-sanjuan commented on tests/Optimizers/JpgOptimizerTest.php
> +     * @runInSeparateProcess
Tratemos de tomar esto como un patrón a tratar de evitar. El uso de `static`, en general es algo que queremos evitar, y hacerlo también nos ayuda a evitar esto `@runInSeparateProcess`

2021-05-30 00:19 UTC, martin-sanjuan commented on tests/Optimizers/JpgOptimizerTest.php
> +     * @dataProvider providerQuality
Este `dataProvider` nos esta dando el `quality` que solo es usado para la creación de `JpgOptimizer`. Es mas para un test de ese constructor que de la función que estas tratando de probar. 

Si necesitáramos un data provider acá, quizás seria un array de `JpgOptimizer` en lugar del `$quality`

2021-05-30 00:19 UTC, martin-sanjuan commented on tests/Optimizers/JpgOptimizerTest.php
> +        $this->assertTrue(true);
Es raro que tengamos que hacer eso. Si esta, tratemos de repensar el test.

2021-05-30 00:19 UTC, martin-sanjuan commented on tests/Optimizers/JpgOptimizerTest.php
> +    }
Tiene utilidad este test?

2021-06-03 03:55 UTC, jonybecker commented on tests/Optimizers/JpgOptimizerTest.php
> +class JpgOptimizerTest extends TestCase
Refactorice todo y ya no lo necesitamos.

2021-06-03 03:56 UTC, jonybecker commented on tests/Optimizers/JpgOptimizerTest.php
> +    public function testAddOptimizer($quality)
$quality ya no es publico, asi que eliminé el param ese.

2021-06-03 03:57 UTC, jonybecker commented on src/DefaultImageOptimizer.php
> +            $optimizerListService = new OptimizerListService();
Lo cambie a la lista que arma la cadena.

2021-06-03 03:58 UTC, jonybecker commented on src/Optimizers/JpgOptimizer.php
> +    public static $quality = 95;
por el momento no. tampoco que sea estática.

2021-06-03 03:59 UTC, jonybecker commented on src/Optimizers/Factories/Jpegoptim.php
> +class Jpegoptim implements OptimizerFactoryInterface
Estaba basado en los nombres de las librerias que usa de Spatie. Igual ya no tenemos mas este factory.

2021-06-03 03:59 UTC, jonybecker commented on src/Optimizers/Factories/Jpegoptim.php
> +class Jpegoptim implements OptimizerFactoryInterface
Gracias! Eliminé el factory.

2021-06-03 04:00 UTC, jonybecker commented on src/Optimizers/JpgOptimizer.php
> +        $optimizerChain->addOptimizer($jpegOptim);
movi esa logica al service list.

2021-06-03 04:03 UTC, jonybecker commented on src/Optimizers/OptimizerListService.php
> +    ];
Lo moví a una clase separada que arma una lista default. con esto lo desacoplamos del manejador de optimizadores y permitimos que se pueda armar otro optimizador custom desde afuera.
En caso de que no se provea un listado de optimizadores usamos el que se armó internamente.

2021-06-03 04:04 UTC, jonybecker commented on src/Optimizers/JpgOptimizer.php
> +    public static function addOptimizerTo(OptimizerChain &$optimizerChain)
Refactorice todo por completo para evitarlos. solo quedaron estaticos los Factories, que ahora son solo 2.

2021-06-03 17:26 UTC, juanmanuel-perez commented on composer.json
> +        "style:check": "docker-compose -f docker-compose.cli.yml run --rm php-cs-fixer fix --verbose --show-progress=estimating --dry-run",
@ecastro98 te sirven estos scripts para los [workflows](https://github.com/TiendaNube/image-compression-lib/pull/8/files#diff-a73bb6555480a5ee79ae276a3f5d71a08fa316e09a4a8da7b643cf1e92c97df9R11)?

2021-06-03 17:29 UTC, juanmanuel-perez commented on tests/DefaultImageOptimizerTest.php
> +        $exec->expects($this->once())
Aca estoy medio mareado con el core. Funca sin el mockery close del tear down? O habria que agregarlo?

2021-06-03 17:33 UTC, jonybecker commented on tests/DefaultImageOptimizerTest.php
> +        $exec->expects($this->once())
Es un buen punto, pruebo y te aviso.

2021-06-03 18:11 UTC, ecastro98 commented on composer.json
> +        "style:check": "docker-compose -f docker-compose.cli.yml run --rm php-cs-fixer fix --verbose --show-progress=estimating --dry-run",
No, tendría que tener instalado composer para correr estos comandos (osea para `composer style:check`)

2021-06-03 18:37 UTC, juanmanuel-perez commented on composer.json
> +        "style:check": "docker-compose -f docker-compose.cli.yml run --rm php-cs-fixer fix --verbose --show-progress=estimating --dry-run",
ahhh claro, no dije nada tonces

2026-01-19 17:22 UTC, closed without merging